version: '3.1'
services:
    webserver:
        image: ninoanthonie/pad:latest
        ports:
            - 80:80
        depends_on:
            - db
    
    db: 
        image: mariadb:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: W@chtw00rd123
        volumes:
            - ./database.sql:/docker-entrypoint-initdb.d/database.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8080:80
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
          - PMA_USER=root
          - PMA_PASSWORD=W@chtw00rd123
          
        
      