version: '2.2'
services:
    webserver:
        image: httpd:latest
        ports:
            - 80:80
        depends_on:
            - db
    db: 
        image: mariadb:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: W@chtw00rd123
      