version: '3.1'
services:
    webserver:
        image: ninoanthonie/pad:latest
        ports:
            - 80:80
        volumes: 
            - ./Website/:/var/www/html
        depends_on:
            - db
    
    db: 
        image: mariadb:latest
        ports:
            - 3306:3306
        environment:
            MYSQL_USER: pad
            MYSQL_PASSWORD: Cybersec2021
            MARIADB_ROOT_PASSWORD: Wachtwoord123
        volumes:
            - ./pad.sql:/docker-entrypoint-initdb.d/database.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8080:80
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=db
          - PMA_USER=pad
          - PMA_PASSWORD=Cybersec2021
          
        
      